### ISSUE TITLE
Sometimes the CIK is overwritten with the response string

### ISSUE THREAD

**Issue by maanenson** [exosite-garage/arduino_exosite_library#3]
For example, if I have a response string that is d13=0, the the requests to Exosite API start having a CIK of 'd13=0'. 

Have only seen this when using provisioning to activate as a client model and store the CIK.  If I re-enable that device and generate a new CIK, the unit correctly re-activates, gets the new CIK, and runs correctly again.

**Comment by azdle** [comment]
This should be fixed by 47b00a4c2d4d744b4b9523eaeba6a9ddb98805de released back in march. Haven't seen any reports of this in awhile, closing.
